In [16]:
# Import the needed packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler

In [ ]:
# Import the dataset
dataframe = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/00374/energydata_complete.csv')

In [ ]:
dataframe.head()

In [17]:
my_dataframe = pd.read_csv('energydata_complete.csv')

In [18]:
# View the head of the dataframe
my_dataframe.head()

date  Appliances  lights     T1       RH_1    T2       RH_2  \
0  2016-01-11 17:00:00          60      30  19.89  47.596667  19.2  44.790000   
1  2016-01-11 17:10:00          60      30  19.89  46.693333  19.2  44.722500   
2  2016-01-11 17:20:00          50      30  19.89  46.300000  19.2  44.626667   
3  2016-01-11 17:30:00          50      40  19.89  46.066667  19.2  44.590000   
4  2016-01-11 17:40:00          60      40  19.89  46.333333  19.2  44.530000   

      T3       RH_3         T4  ...         T9   RH_9     T_out  Press_mm_hg  \
0  19.79  44.730000  19.000000  ...  17.033333  45.53  6.600000        733.5   
1  19.79  44.790000  19.000000  ...  17.066667  45.56  6.483333        733.6   
2  19.79  44.933333  18.926667  ...  17.000000  45.50  6.366667        733.7   
3  19.79  45.000000  18.890000  ...  17.000000  45.40  6.250000        733.8   
4  19.79  45.000000  18.890000  ...  17.000000  45.40  6.133333        733.9   

   RH_out  Windspeed  Visibility  Tdewpoint        rv1        rv2  
0    92.0   7.000000   63.000000        5.3  13.275433  13.275433  
1    92.0   6.666667   59.166667        5.2  18.606195  18.606195  
2    92.0   6.333333   55.333333        5.1  28.642668  28.642668  
3    92.0   6.000000   51.500000        5.0  45.410389  45.410389  
4    92.0   5.666667   47.666667        4.9  10.084097  10.084097  

[5 rows x 29 columns]

In [19]:
# Drop the unnecessary dataframes
my_dataframe.drop(['date', 'lights'], axis=1, inplace=True)

In [20]:
# View dataframe
my_dataframe

Appliances         T1       RH_1         T2       RH_2         T3  \
0              60  19.890000  47.596667  19.200000  44.790000  19.790000   
1              60  19.890000  46.693333  19.200000  44.722500  19.790000   
2              50  19.890000  46.300000  19.200000  44.626667  19.790000   
3              50  19.890000  46.066667  19.200000  44.590000  19.790000   
4              60  19.890000  46.333333  19.200000  44.530000  19.790000   
...           ...        ...        ...        ...        ...        ...   
19730         100  25.566667  46.560000  25.890000  42.025714  27.200000   
19731          90  25.500000  46.500000  25.754000  42.080000  27.133333   
19732         270  25.500000  46.596667  25.628571  42.768571  27.050000   
19733         420  25.500000  46.990000  25.414000  43.036000  26.890000   
19734         430  25.500000  46.600000  25.264286  42.971429  26.823333   

            RH_3         T4       RH_4         T5  ...         T9     RH_9  \
0      44.730000  19.000000  45.566667  17.166667  ...  17.033333  45.5300   
1      44.790000  19.000000  45.992500  17.166667  ...  17.066667  45.5600   
2      44.933333  18.926667  45.890000  17.166667  ...  17.000000  45.5000   
3      45.000000  18.890000  45.723333  17.166667  ...  17.000000  45.4000   
4      45.000000  18.890000  45.530000  17.200000  ...  17.000000  45.4000   
...          ...        ...        ...        ...  ...        ...      ...   
19730  41.163333  24.700000  45.590000  23.200000  ...  23.200000  46.7900   
19731  41.223333  24.700000  45.590000  23.230000  ...  23.200000  46.7900   
19732  41.690000  24.700000  45.730000  23.230000  ...  23.200000  46.7900   
19733  41.290000  24.700000  45.790000  23.200000  ...  23.200000  46.8175   
19734  41.156667  24.700000  45.963333  23.200000  ...  23.200000  46.8450   

           T_out  Press_mm_hg     RH_out  Windspeed  Visibility  Tdewpoint  \
0       6.600000        733.5  92.000000   7.000000   63.000000   5.300000   
1       6.483333        733.6  92.000000   6.666667   59.166667   5.200000   
2       6.366667        733.7  92.000000   6.333333   55.333333   5.100000   
3       6.250000        733.8  92.000000   6.000000   51.500000   5.000000   
4       6.133333        733.9  92.000000   5.666667   47.666667   4.900000   
...          ...          ...        ...        ...         ...        ...   
19730  22.733333        755.2  55.666667   3.333333   23.666667  13.333333   
19731  22.600000        755.2  56.000000   3.500000   24.500000  13.300000   
19732  22.466667        755.2  56.333333   3.666667   25.333333  13.266667   
19733  22.333333        755.2  56.666667   3.833333   26.166667  13.233333   
19734  22.200000        755.2  57.000000   4.000000   27.000000  13.200000   

             rv1        rv2  
0      13.275433  13.275433  
1      18.606195  18.606195  
2      28.642668  28.642668  
3      45.410389  45.410389  
4      10.084097  10.084097  
...          ...        ...  
19730  43.096812  43.096812  
19731  49.282940  49.282940  
19732  29.199117  29.199117  
19733   6.322784   6.322784  
19734  34.118851  34.118851  

[19735 rows x 27 columns]

In [21]:
# Import train_test_split
from sklearn.model_selection import train_test_split

In [23]:
# Set the appliances column as the target
target = my_dataframe['Appliances'].values
my_dataframe.drop(['Appliances'], axis=1, inplace=True)

In [24]:
# Set testing data
cols = list(my_dataframe.columns)
test = my_dataframe[cols].values

In [64]:
test.shape

(19735, 26)

In [65]:
target.shape

(19735,)

In [25]:
# Split the dataset into training and testing set
x_train, x_test, y_train, y_test = train_test_split(test, target, test_size=0.3, random_state=42)

In [26]:
# Begin training the regression model
linear_model = LinearRegression()
linear_model.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [27]:
# Make predictions
predicted = linear_model.predict(x_test)

In [28]:
predicted

array([ 45.54761868, 271.20410666,  46.38025696, ...,  83.23836265,
       117.34588177,  71.22751965])

In [29]:
#Calculate for the Mean Absolute Error
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, predicted)
round(mae, 2)

53.64

In [46]:
x = my_dataframe['T2'].values.reshape(-1,1)
y = my_dataframe['T6'].values.reshape(-1,1)

In [47]:
x_trains, x_tests, y_trains, y_tests = train_test_split(x, y, test_size=0.3, random_state=42)

In [48]:
new_model = LinearRegression()
new_model.fit(x_trains, y_trains)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [49]:
my_prediction = new_model.predict(x_tests)

In [50]:
my_prediction

array([[ 2.15578912],
       [10.01116055],
       [ 1.87391554],
       ...,
       [ 4.24758774],
       [ 8.69822311],
       [ 4.9893603 ]])

In [51]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [53]:
round(r2_score(y_tests, my_prediction), 2)

0.64

In [54]:
round(mean_absolute_error(y_tests, my_prediction), 2)

2.82

In [55]:
rss = np.sum(np.square(y_tests-my_prediction))

In [57]:
round(rss,2)

78033.97

In [59]:
round(np.sqrt(mean_squared_error(y_tests,my_prediction)),3)

3.63

In [62]:
round(r2_score(y_tests,my_prediction),2)

0.64

In [63]:
new_model.coef_

array([[2.22531769]])

In [69]:
np.argmin(linear_model.coef_)

16

In [70]:
np.argmax(linear_model.coef_)

4

In [73]:
my_dataframe[cols].columns[[16,4]]

Index(['T9', 'T3'], dtype='object')

In [74]:
from sklearn.linear_model import Ridge,Lasso

In [77]:
new_model2 = Ridge(alpha=0.4)

In [78]:
new_model2.fit(x_trains,y_trains)

Ridge(alpha=0.4, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [79]:
my_prediction2 = new_model2.predict(x_tests)

In [80]:
round(np.sqrt(mean_squared_error(y_tests,my_prediction2)),2)

3.63

In [81]:
linear_model_lasso = Lasso(alpha=0.001)

In [83]:
linear_model_lasso.fit(x_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 6136226.882484287, tolerance: 14642.917148544962
  positive)


Lasso(alpha=0.001, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [84]:
lasso_pred = linear_model_lasso.predict(x_test)

In [88]:
linear_model_lasso.coef_[linear_model_lasso.coef_>0].shape

(16,)

In [90]:
round(np.sqrt(mean_squared_error(y_test,lasso_pred)),3)

93.64